-- Cached instrument universe sourced from the Toss Securities Open API.
-- This table contains public market metadata only; it has no user/account data.
create table if not exists public.instrument_search_index (
  id bigint generated by default as identity primary key,
  symbol text not null,
  name text not null,
  market text not null,
  security_type text,
  isin_code text,
  source text not null default 'tossinvest',
  synced_at timestamptz not null default now(),
  unique (market, symbol)
);

create index if not exists instrument_search_index_symbol_idx
  on public.instrument_search_index (symbol);
create index if not exists instrument_search_index_name_idx
  on public.instrument_search_index (name);
create index if not exists instrument_search_index_market_idx
  on public.instrument_search_index (market);

alter table public.instrument_search_index enable row level security;
drop policy if exists "public can read instrument search index" on public.instrument_search_index;
create policy "public can read instrument search index"
  on public.instrument_search_index for select using (true);
